name: jenseplensPlugin
version: 1.1
description: Plugin voor jenseplens zijn server
main: me.jenseplens.jenseplensPlugin.JenseplensPlugin

commands:
  staff:
    description: Laat stafflijst zien
  locatie:
    description: Laat je locatie zien
