name: jenseplensPlugin
version: 1.0
description: Plugin gemaakt door jenseplens
main: me.jenseplens.jenseplensPlugin.JenseplensPlugin

commands:
  jenseplens:
    description: Geeft informatie over jenseplens
  staff:
    description: Laat stafflijst zien
  locatie:
    description: Laat je locatie zien
  jenseplenspluginreload:
    description: Reload de jenseplensPlugin
